// Note: this file is not yet in use.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNWw0U0XLmmv6ODN5MbjsLG63wT2dQf8w',
    appId: '1:784395573848:web:70d4a7de1467efd82d082d',
    messagingSenderId: '784395573848',
    projectId: 'park-lock-app-backend',
    authDomain: 'park-lock-app-backend.firebaseapp.com',
    databaseURL:
        'https://park-lock-app-backend-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'park-lock-app-backend.appspot.com',
    measurementId: 'G-DMLCCRY2PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAxehCKIsBo3ZOMsIMERyfV7XnaU0V3GM',
    appId: '1:784395573848:android:087c8d8edc911c192d082d',
    messagingSenderId: '784395573848',
    projectId: 'park-lock-app-backend',
    databaseURL:
        'https://park-lock-app-backend-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'park-lock-app-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiu15dnx2UmT1hEZ8k0udN7lIIRINMDDw',
    appId: '1:784395573848:ios:0442246f4b59a48b2d082d',
    messagingSenderId: '784395573848',
    projectId: 'park-lock-app-backend',
    databaseURL:
        'https://park-lock-app-backend-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'park-lock-app-backend.appspot.com',
    iosClientId:
        '784395573848-e9969k7o5jeagnv87ivegnms5pn8nks2.apps.googleusercontent.com',
    iosBundleId: 'com.example.parklock',
  );
}
